---
title: "Template RJob ZKWappDataExport"
subtitle: "findGateNamesCellCount"
author: "Your Name"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    code_folding: hide
    df_print: paged
    fig_caption: yes
    highlight: haddock
    theme: cosmo
    toc: yes
    toc_float:
      collapsed: no
      smooth_scoll: yes
abstract: "The aim of this "
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      eval = FALSE)
options(stringsAsFactors = FALSE)
options(rmarkdown.html_vignette.check_title = FALSE)

library(RJobZKWappDataExport)
conflicted::conflict_prefer("find_valid_group_chip_IDs", "RJobZKWappDataExport")
conflicted::conflict_prefer("create_working_directory", "RJobZKWappDataExport")
```

**set input**

- set chip_group_ID

```{r set chipgroup}
group_ID <- "P1761451"
result_ID <- group_ID
```

- set output directory

```{r set output directory}
output_dir <- "data_output"
```

**get all valid chip_IDs in chip_group**

```{r set or get valid chipIDs}
# get all valid chip_IDs of chipgroup
chip_IDs <- find_valid_group_chip_IDs(group_ID)

# OR type chip_IDs manually
chip_IDs <- c("M911981","M911971")
result_ID <- "man_chipIDs"
```

**find gateNames and CellCount**

```{r find gatenames and cell counts}
gateData <- find_gateName_cellCount(chip_IDs,
                                    output_dir,
                                    result_ID)
```

**calculate tissue area**

```{r estimate tissue area}
tissueArea <- execute_RJobTissueArea(chip_IDs,
                                     output_dir,
                                     result_ID,
                                     sigma = 15,
                                     threshold = 4,
                                     window = 50,
                                     plot_image = TRUE)
```

**export combined Result csv-file**

```{r export combined xls result file}
export_tissueArea_and_gateNamesCellCount(output_dir,result_ID)
```





















# supplement

**export xls with only gate data**

```{r export xls with only gate data}
#load gate data
gateData_file <- create_GateNamesCellCount_Result_filename(output_dir,
                                                             result_ID)
gateData <- data.table::fread(gateData_file)

# create export list
exportList <- create_export_list(gateData)

# export xls file----
filename <- file.path(output_dir,
                      paste0("combinedResults_",result_ID,".xlsx"))
writexl::write_xlsx(exportList,
                    filename,
                    col_names = FALSE)
```

**get sample type**

```{r get sample type}
query_result <- query_UID_limslager(chip_IDs)
EDL <- get_EDLs_of_queryResult(query_result)
nodeset <- get_nodesets_of_EDLs(EDL)
MethodHistory <- extract_MethodHistory(nodeset)
sampleType <- MethodHistory%>%extract_sampleType()
```

