---
title: " documentation - detect tissue area"
subtitle: "reportings on functional development"
author: "Julia Ortmann"
output: 
  html_document:
    code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: '3'
    theme:
      bg: "#202123"
      fg: "#B8BCC2"
      primary: "#EA80FC"
      secondary: "#00DAC6"
      base_font:
        google: Prompt
      heading_font:
        google: Proza Libre
abstract: The aim of this build functions for import of scan HDR images, defined by scan_ID
knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_file = "inst/report/dev report - detect tissue area.html",
      envir = globalenv()
    )
  })
---

```{r setup, include=FALSE}
if (requireNamespace("thematic")) 
  thematic::thematic_rmd(font = "auto")
```

# summary

... 

# introduction 

# supplement

## 

- pos 11 of chip M1730408, load all hdr's
- sum pixel intensities
- export data matrix as data.table 
```{r}
#for testing
library(magrittr)
library(ggplot2)
file <- file.path("inst/data","data_sum_M1730408_pos11.csv")
data.sum <- data.table::fread(file)
m.data_sum <- data.sum%>% as.matrix()
long.data_sm <- reshape::melt(m.data_sum)
ggplot(long.data_sm, aes(x = X2, y = X1)) + 
  geom_raster(aes(fill=value))

```

```{r}
library(imager)
eps <- seq(5000,10000,1000)#c(0.001,0.01,0.1,1,10,50,100,500,1000,5000) #eps
minPts <- c(1:20)#,10,100,1000,10000) #minPts

i=1
j=10
colnames(m.data_sum) <- stringr::str_remove_all("V",colnames(m.data_sum))
collect_cluster <- reshape::melt(m.data_sum)
collect_cluster$X2 <- as.character(collect_cluster$X2)
colnames(collect_cluster)<-c("x","y","value")
#data_cmg <-as.cimg(collect_cluster)
image(log(m.data_sum), useRaster=TRUE, axes=FALSE)

for(i in eps){
  
  for( j in minPts){
    
    dbscan_result<-dbscan::dbscan(log(data.sum),
                                  eps=i,
                                  minPts=j)
    
    long.data_sm$cluster <- as.factor(dbscan_result$cluster)
    long.data_sm$value <- log( long.data_sm$value)
    writeLines(paste0("log scale - eps = ",i," - minPts = ",j," - #cluster: ",length(table(dbscan_result$cluster))))
    
   p <- ggplot(long.data_sm)+
     #geom_raster(aes(x = X2, y = X1, fill=value),alpha=0.5)+ 
     geom_raster(aes(x = X2, y = X1,color =cluster, fill=value),alpha=0.5)
   #   #scale_color_discrete()+
   #   #scale_color_continuous()+
   #   
   #   
   #   
   ##   #geom_raster(),alpha=0.5)+
   ##   #scale_alpha_discrete()+
   ##   # geom_raster(aes(x = X2, y = X1, fill = value),alpha=0.5)+
   ##   #geom_raster(aes(fill=cluster))+
   ## # scale_fill_manual(name = "Land cover",
   ## #               values = long.data_sm$cluster,
   ## #               labels = long.data_sm$cluster,
   ## #               na.translate = FALSE)+
   # #ggtitle()
   ## #   ?scale_fill_gradient(low="grey90", high="red")+
   ##   
   ## 
   print(p)
    # 
   
   
    collect_cluster <- cbind(collect_cluster,dbscan_result$cluster)
  }
}
```
