---
title: "HowToUse"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{HowToUse}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
usethis::proj_set()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache=FALSE
)

knitr::opts_knit$set(cache=FALSE,
                     root.dir=file.path(getwd()),
                     base.dir=file.path(getwd())
)

here::here()
here::i_am("vignettes/HowToUse.Rmd")

```

```{r setup}
library(RJobTissueArea)
```

- get all valid chip_IDs defined in chip_group 

```{r,eval=FALSE}
group_ID <- "P1761451"
chip_IDs <- find_valid_group_chip_IDs(group_ID)
```

- get all image files

```{r,eval=FALSE}
image_files <- list_all_image_files(chip_IDs)
```

- export result table

```{r,eval=FALSE}

output_dir <- "inst/data_output"
if(dir.exists(output_dir)==FALSE){
  dir.create(output_dir)
}

data.table::fwrite(image_files,
                  file.path(
                    output_dir,
                    paste0("all_image_files_of_groupID_",group_ID,".csv")))

feather::write_feather(image_files,
                  file.path(
                    output_dir,
                    paste0("all_image_files_of_groupID_",group_ID,".feather")))
```

- select valid bolb32 files

```{r,eval=FALSE}
blob32_files <- select_valid_image_files(image_files,
                                         type = "blob32")
```

